name: CI Builds of DifferentMod Free Edition

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup CI workspace for building
      run: ./gradlew setupCiWorkspace
    - name: Build the JAR
      run: ./gradlew build
    - name: Upload built file
      uses: actions/upload-artifact@v2
      with:
        name: DifferentMod-Free-Edition-Archive
        path: ./build/libs/*.jar
